from . import views
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView

urlpatterns = [
    path('redirect-admin', RedirectView.as_view(url="/admin"),name="redirect-admin"),
    path('', views.home, name="home-page"),
    path('login/', auth_views.LoginView.as_view(
        template_name="login.html",
        redirect_authenticated_user=True
    ), name='login'),
    path('userlogin/', views.login_user, name="login-user"),
    path('logout/', views.logoutuser, name='logout'),
    path('profile',views.profile,name='profile'),
    path('update-profile',views.update_profile,name='update-profile'),
    path('update-avatar',views.update_avatar,name='update-avatar'),
    path('update-password',views.update_password,name='update-password'),
    path('department',views.department,name='department-page'),
    path('manage_department/', views.manage_department, name='manage-department-modal'),
    path('manage_department/<int:pk>/', views.manage_department, name='manage-department-modal'),
    path('save_department/', views.save_department, name='save-department'),
    path('delete_department/', views.delete_department, name='delete-department'),
    path('course',views.course,name='course-page'),
    path('manage_course', views.manage_course, name='manage-course-modal'),
    path('manage_course/<int:pk>', views.manage_course, name='manage-course-modal'),
    path('save_course', views.save_course, name='save-course'),
    path('delete_course', views.delete_course, name='delete-course'),
    path('faculty/', views.faculty, name='faculty-page'),
    path('manage-faculty/', views.manage_faculty, name='manage-faculty'),
    path('manage-faculty/<int:pk>/', views.manage_faculty, name='manage-faculty-edit'),
    path('save-faculty/', views.save_faculty, name='save-faculty'),
    path('delete-faculty/', views.delete_faculty, name='delete-faculty'),
    path('class',views.classPage,name='class-page'),
    path('manage_class',views.manage_class,name='manage-class-modal'),
    path(r'manage_class/<int:pk>',views.manage_class,name='edit-class-modal'),
    path(r'manage_class_student/<int:classPK>',views.manage_class_student,name='class-student-modal'),
    path('save_class_student/',views.save_class_student,name='save-class-student'),
    path(r'view_class/<int:pk>',views.view_class,name='class-page'),
    path('save_class',views.save_class,name='save-class'),
    path('delete_class',views.delete_class,name='delete-class'),
    path('delete_class_student',views.delete_class_student,name='delete-class-student'),
    path('student/', views.student, name='student-page'),
    path('student/manage/', views.manage_student, name='manage-student'),
    path('student/manage/<int:pk>/', views.manage_student, name='edit-student'),
    path('student/view/<int:pk>/', views.view_student, name='view-student'),
    path('student/delete/', views.delete_student, name='delete-student'),
    path('student/save/', views.save_student, name='save-student'),
    path('import-students/', views.import_students, name='import-students'),
    path('attendance_class',views.attendance_class,name='attendance-class'),
    path('attendance/<int:classPK>/', views.attendance, name='attendance-page'),
    path('attendance/<int:classPK>/<str:date>/', views.attendance, name='attendance-page-date'),
    path('save_attendance',views.save_attendance,name='save-attendance'),
    path('export-data/', views.export_data, name='export-data'),
    path('process-bulk-upload/', views.process_bulk_upload, name='process-bulk-upload'),
    path('leave-application/', views.leave_application, name='leave-application'),
    path('leave-application/submit/', views.submit_leave, name='submit-leave'),
    path('feedback/', views.submit_feedback, name='feedback'),
    path('feedback/submit/', views.submit_feedback, name='submit-feedback'),
    path('create-default-courses/', views.create_default_courses, name='create-default-courses'),
    path('create-sample-classes/', views.create_sample_classes, name='create-sample-classes'),
    path('academic-units/', views.academic_units, name='academic-units'),
    path('register/', views.register, name='register'),
    path('create-default-users/', views.create_default_users, name='create-default-users'),
    path('student/schedule/', views.class_schedule, name='class-schedule'),
    path('student/attendance/', views.student_attendance, name='student-attendance'),
    path('student/feedback/', views.submit_feedback, name='feedback'),
    path('student/leave/', views.leave_application, name='leave-application'),
    path('profile/', views.profile, name='profile'),
    path('profile/update/', views.update_profile, name='update-profile'),
    path('faculty/feedback/', views.faculty_feedback, name='faculty-feedback'),
    path('faculty/leave-applications/', views.faculty_leave_applications, name='faculty-leave-applications'),
    path('faculty/update-leave-status/', views.update_leave_status, name='update-leave-status'),
    path('student/mark-attendance/', views.mark_student_attendance, name='mark-student-attendance'),
    path('class/<int:pk>/view/', views.view_class, name='view-class'),
    path('faculty/data-management/', views.faculty_data_management, name='faculty-data-management'),
    path('faculty/export-attendance/', views.export_attendance, name='export-attendance'),
    path('faculty/import-attendance/', views.import_attendance, name='import-attendance'),
    path('update-student-names/', views.update_student_names, name='update-student-names'),
    path('reports/', views.reports, name='reports'),
    path('generate-report/', views.generate_report, name='generate-report'),
    path('search-students/', views.search_students, name='search-students'),
    path('admin-search/', views.admin_search, name='admin-search'),
    path('import-students/', views.import_students, name='import-students'),
    path('admin-download-template/', views.admin_download_template, name='admin-download-template'),
    path('faculty-download-template/', views.faculty_download_template, name='faculty-download-template'),
    path('import-faculty/', views.import_faculty, name='import-faculty'),
    path('faculty/students/', views.faculty_students, name='faculty-students'),
    path('faculty/add-student/', views.faculty_add_student, name='faculty-add-student'),
    path('faculty/import-students/', views.faculty_import_students, name='faculty-import-students'),
]
